name: deploy-stack-traefik-failover.yaml
on:
  push:
    paths:
      - stacks/traefik-failover/**
  workflow_call: null
  workflow_dispatch: null
env:
  AUTHENTIK_INSECURE: "false"
  AUTHENTIK_TOKEN: ${{ secrets.AUTHENTIK_TOKEN }}
  AUTHENTIK_URL: https://login.sapslaj.cloud
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: us-east-1
  AWS_REGION: us-east-1
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
  CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
  GH_ACTIONS_READ_TOKEN: ${{ secrets.GH_ACTIONS_READ_TOKEN }}
  INFISICAL_API_URL: https://infisical.sapslaj.cloud/api
  INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
  INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
  INFISICAL_HOST: https://infisical.sapslaj.cloud
  INFISICAL_UNIVERSAL_AUTH_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
  INFISICAL_UNIVERSAL_AUTH_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
  NODE_AUTH_TOKEN: ${{ secrets.GH_ACTIONS_READ_TOKEN }}
  PROXMOX_VE_ENDPOINT: ${{ secrets.PROXMOX_VE_ENDPOINT }}
  PROXMOX_VE_INSECURE: "true"
  PROXMOX_VE_PASSWORD: ${{ secrets.PROXMOX_VE_PASSWORD }}
  PROXMOX_VE_USERNAME: ${{ secrets.PROXMOX_VE_USERNAME }}
  PULUMI_CONFIG_PASSPHRASE: ""
  RUNNER_TOOL_CACHE: /toolcache
  TAILSCALE_API_KEY: ${{ secrets.TAILSCALE_API_KEY }}
  VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
  VYOS_HOST: ${{ secrets.VYOS_HOST }}
  VYOS_PASSWORD: ${{ secrets.VYOS_PASSWORD }}
  VYOS_USERNAME: ${{ secrets.VYOS_USERNAME }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: package-lock.json
          registry-url: https://npm.pkg.github.com
          token: ${{ env.GH_ACTIONS_READ_TOKEN }}
      - run: npm ci --ignore-scripts
      - name: Create pulumi-state AWS profile
        shell: bash
        run: |
          mkdir -p ~/.aws
          cat >> ~/.aws/credentials << EOF
          [pulumi-state]
          aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EOF
          cat >> ~/.aws/config << EOF
          [profile pulumi-state]
          region=us-east-1
          output=json
          EOF
      - uses: pulumi/actions@v6
        with:
          command: ${{ github.ref_name == 'main' && 'up' || 'preview' }}
          stack-name: prod
          cloud-url: s3://sapslaj-tf-state?region=us-east-1&awssdk=v2&profile=pulumi-state
          work-dir: ./stacks/traefik-failover
          github-token: ${{ env.GH_ACTIONS_READ_TOKEN }}
