# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguardhome-sync
  labels:
    app: adguardhome-sync
spec:
  selector:
    matchLabels:
      app: adguardhome-sync
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: adguardhome-sync
    spec:
      restartPolicy: Always
      containers:
        - name: adguardhome-sync
          image: ghcr.io/bakito/adguardhome-sync:latest
          args:
            - run
            - --config
            - /config/adguardhome-sync.yaml
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
          env:
            - name: LOG_FORMAT
              value: json
            - name: ORIGIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: adguardhome-sync-credentials
                  key: username
            - name: ORIGIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: adguardhome-sync-credentials
                  key: password
            - name: REPLICA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: adguardhome-sync-credentials
                  key: username
            - name: REPLICA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: adguardhome-sync-credentials
                  key: password
          resources:
            requests:
              memory: 100Mi
            limits:
              cpu: "1"
              memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 8080
              name: http
      volumes:
        - name: config
          configMap:
            name: adguardhome-sync
