// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class PropertyMappingProviderSaml extends pulumi.CustomResource {
    /**
     * Get an existing PropertyMappingProviderSaml resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PropertyMappingProviderSamlState, opts?: pulumi.CustomResourceOptions): PropertyMappingProviderSaml {
        return new PropertyMappingProviderSaml(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/propertyMappingProviderSaml:PropertyMappingProviderSaml';

    /**
     * Returns true if the given object is an instance of PropertyMappingProviderSaml.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PropertyMappingProviderSaml {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PropertyMappingProviderSaml.__pulumiType;
    }

    public readonly expression!: pulumi.Output<string>;
    public readonly friendlyName!: pulumi.Output<string | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly propertyMappingProviderSamlId!: pulumi.Output<string>;
    public readonly samlName!: pulumi.Output<string>;

    /**
     * Create a PropertyMappingProviderSaml resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PropertyMappingProviderSamlArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PropertyMappingProviderSamlArgs | PropertyMappingProviderSamlState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PropertyMappingProviderSamlState | undefined;
            resourceInputs["expression"] = state ? state.expression : undefined;
            resourceInputs["friendlyName"] = state ? state.friendlyName : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["propertyMappingProviderSamlId"] = state ? state.propertyMappingProviderSamlId : undefined;
            resourceInputs["samlName"] = state ? state.samlName : undefined;
        } else {
            const args = argsOrState as PropertyMappingProviderSamlArgs | undefined;
            if ((!args || args.expression === undefined) && !opts.urn) {
                throw new Error("Missing required property 'expression'");
            }
            if ((!args || args.samlName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'samlName'");
            }
            resourceInputs["expression"] = args ? args.expression : undefined;
            resourceInputs["friendlyName"] = args ? args.friendlyName : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["propertyMappingProviderSamlId"] = args ? args.propertyMappingProviderSamlId : undefined;
            resourceInputs["samlName"] = args ? args.samlName : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PropertyMappingProviderSaml.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering PropertyMappingProviderSaml resources.
 */
export interface PropertyMappingProviderSamlState {
    expression?: pulumi.Input<string>;
    friendlyName?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    propertyMappingProviderSamlId?: pulumi.Input<string>;
    samlName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a PropertyMappingProviderSaml resource.
 */
export interface PropertyMappingProviderSamlArgs {
    expression: pulumi.Input<string>;
    friendlyName?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    propertyMappingProviderSamlId?: pulumi.Input<string>;
    samlName: pulumi.Input<string>;
}
