// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class PropertyMappingProviderScope extends pulumi.CustomResource {
    /**
     * Get an existing PropertyMappingProviderScope resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PropertyMappingProviderScopeState, opts?: pulumi.CustomResourceOptions): PropertyMappingProviderScope {
        return new PropertyMappingProviderScope(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/propertyMappingProviderScope:PropertyMappingProviderScope';

    /**
     * Returns true if the given object is an instance of PropertyMappingProviderScope.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PropertyMappingProviderScope {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PropertyMappingProviderScope.__pulumiType;
    }

    public readonly description!: pulumi.Output<string | undefined>;
    public readonly expression!: pulumi.Output<string>;
    public readonly name!: pulumi.Output<string>;
    public readonly propertyMappingProviderScopeId!: pulumi.Output<string>;
    public readonly scopeName!: pulumi.Output<string>;

    /**
     * Create a PropertyMappingProviderScope resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PropertyMappingProviderScopeArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PropertyMappingProviderScopeArgs | PropertyMappingProviderScopeState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PropertyMappingProviderScopeState | undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["expression"] = state ? state.expression : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["propertyMappingProviderScopeId"] = state ? state.propertyMappingProviderScopeId : undefined;
            resourceInputs["scopeName"] = state ? state.scopeName : undefined;
        } else {
            const args = argsOrState as PropertyMappingProviderScopeArgs | undefined;
            if ((!args || args.expression === undefined) && !opts.urn) {
                throw new Error("Missing required property 'expression'");
            }
            if ((!args || args.scopeName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'scopeName'");
            }
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["expression"] = args ? args.expression : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["propertyMappingProviderScopeId"] = args ? args.propertyMappingProviderScopeId : undefined;
            resourceInputs["scopeName"] = args ? args.scopeName : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PropertyMappingProviderScope.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering PropertyMappingProviderScope resources.
 */
export interface PropertyMappingProviderScopeState {
    description?: pulumi.Input<string>;
    expression?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    propertyMappingProviderScopeId?: pulumi.Input<string>;
    scopeName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a PropertyMappingProviderScope resource.
 */
export interface PropertyMappingProviderScopeArgs {
    description?: pulumi.Input<string>;
    expression: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    propertyMappingProviderScopeId?: pulumi.Input<string>;
    scopeName: pulumi.Input<string>;
}
