// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ProviderGoogleWorkspace extends pulumi.CustomResource {
    /**
     * Get an existing ProviderGoogleWorkspace resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProviderGoogleWorkspaceState, opts?: pulumi.CustomResourceOptions): ProviderGoogleWorkspace {
        return new ProviderGoogleWorkspace(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/providerGoogleWorkspace:ProviderGoogleWorkspace';

    /**
     * Returns true if the given object is an instance of ProviderGoogleWorkspace.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProviderGoogleWorkspace {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProviderGoogleWorkspace.__pulumiType;
    }

    /**
     * JSON format expected. Use jsonencode() to pass objects. Defaults to `{}`.
     */
    public readonly credentials!: pulumi.Output<string | undefined>;
    public readonly defaultGroupEmailDomain!: pulumi.Output<string>;
    /**
     * Defaults to `seconds=0`.
     */
    public readonly delegatedSubject!: pulumi.Output<string | undefined>;
    /**
     * Defaults to `false`.
     */
    public readonly dryRun!: pulumi.Output<boolean | undefined>;
    public readonly excludeUsersServiceAccount!: pulumi.Output<boolean | undefined>;
    public readonly filterGroup!: pulumi.Output<string | undefined>;
    /**
     * Allowed values: - `delete` - `do_nothing` Defaults to `delete`.
     */
    public readonly groupDeleteAction!: pulumi.Output<string | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly propertyMappings!: pulumi.Output<string[] | undefined>;
    public readonly propertyMappingsGroups!: pulumi.Output<string[] | undefined>;
    public readonly providerGoogleWorkspaceId!: pulumi.Output<string>;
    /**
     * Allowed values: - `do_nothing` - `delete` - `suspend` Defaults to `delete`.
     */
    public readonly userDeleteAction!: pulumi.Output<string | undefined>;

    /**
     * Create a ProviderGoogleWorkspace resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderGoogleWorkspaceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProviderGoogleWorkspaceArgs | ProviderGoogleWorkspaceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProviderGoogleWorkspaceState | undefined;
            resourceInputs["credentials"] = state ? state.credentials : undefined;
            resourceInputs["defaultGroupEmailDomain"] = state ? state.defaultGroupEmailDomain : undefined;
            resourceInputs["delegatedSubject"] = state ? state.delegatedSubject : undefined;
            resourceInputs["dryRun"] = state ? state.dryRun : undefined;
            resourceInputs["excludeUsersServiceAccount"] = state ? state.excludeUsersServiceAccount : undefined;
            resourceInputs["filterGroup"] = state ? state.filterGroup : undefined;
            resourceInputs["groupDeleteAction"] = state ? state.groupDeleteAction : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["propertyMappings"] = state ? state.propertyMappings : undefined;
            resourceInputs["propertyMappingsGroups"] = state ? state.propertyMappingsGroups : undefined;
            resourceInputs["providerGoogleWorkspaceId"] = state ? state.providerGoogleWorkspaceId : undefined;
            resourceInputs["userDeleteAction"] = state ? state.userDeleteAction : undefined;
        } else {
            const args = argsOrState as ProviderGoogleWorkspaceArgs | undefined;
            if ((!args || args.defaultGroupEmailDomain === undefined) && !opts.urn) {
                throw new Error("Missing required property 'defaultGroupEmailDomain'");
            }
            resourceInputs["credentials"] = args ? args.credentials : undefined;
            resourceInputs["defaultGroupEmailDomain"] = args ? args.defaultGroupEmailDomain : undefined;
            resourceInputs["delegatedSubject"] = args ? args.delegatedSubject : undefined;
            resourceInputs["dryRun"] = args ? args.dryRun : undefined;
            resourceInputs["excludeUsersServiceAccount"] = args ? args.excludeUsersServiceAccount : undefined;
            resourceInputs["filterGroup"] = args ? args.filterGroup : undefined;
            resourceInputs["groupDeleteAction"] = args ? args.groupDeleteAction : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["propertyMappings"] = args ? args.propertyMappings : undefined;
            resourceInputs["propertyMappingsGroups"] = args ? args.propertyMappingsGroups : undefined;
            resourceInputs["providerGoogleWorkspaceId"] = args ? args.providerGoogleWorkspaceId : undefined;
            resourceInputs["userDeleteAction"] = args ? args.userDeleteAction : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ProviderGoogleWorkspace.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ProviderGoogleWorkspace resources.
 */
export interface ProviderGoogleWorkspaceState {
    /**
     * JSON format expected. Use jsonencode() to pass objects. Defaults to `{}`.
     */
    credentials?: pulumi.Input<string>;
    defaultGroupEmailDomain?: pulumi.Input<string>;
    /**
     * Defaults to `seconds=0`.
     */
    delegatedSubject?: pulumi.Input<string>;
    /**
     * Defaults to `false`.
     */
    dryRun?: pulumi.Input<boolean>;
    excludeUsersServiceAccount?: pulumi.Input<boolean>;
    filterGroup?: pulumi.Input<string>;
    /**
     * Allowed values: - `delete` - `do_nothing` Defaults to `delete`.
     */
    groupDeleteAction?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    propertyMappings?: pulumi.Input<pulumi.Input<string>[]>;
    propertyMappingsGroups?: pulumi.Input<pulumi.Input<string>[]>;
    providerGoogleWorkspaceId?: pulumi.Input<string>;
    /**
     * Allowed values: - `do_nothing` - `delete` - `suspend` Defaults to `delete`.
     */
    userDeleteAction?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ProviderGoogleWorkspace resource.
 */
export interface ProviderGoogleWorkspaceArgs {
    /**
     * JSON format expected. Use jsonencode() to pass objects. Defaults to `{}`.
     */
    credentials?: pulumi.Input<string>;
    defaultGroupEmailDomain: pulumi.Input<string>;
    /**
     * Defaults to `seconds=0`.
     */
    delegatedSubject?: pulumi.Input<string>;
    /**
     * Defaults to `false`.
     */
    dryRun?: pulumi.Input<boolean>;
    excludeUsersServiceAccount?: pulumi.Input<boolean>;
    filterGroup?: pulumi.Input<string>;
    /**
     * Allowed values: - `delete` - `do_nothing` Defaults to `delete`.
     */
    groupDeleteAction?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    propertyMappings?: pulumi.Input<pulumi.Input<string>[]>;
    propertyMappingsGroups?: pulumi.Input<pulumi.Input<string>[]>;
    providerGoogleWorkspaceId?: pulumi.Input<string>;
    /**
     * Allowed values: - `do_nothing` - `delete` - `suspend` Defaults to `delete`.
     */
    userDeleteAction?: pulumi.Input<string>;
}
