// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ProviderMicrosoftEntra extends pulumi.CustomResource {
    /**
     * Get an existing ProviderMicrosoftEntra resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProviderMicrosoftEntraState, opts?: pulumi.CustomResourceOptions): ProviderMicrosoftEntra {
        return new ProviderMicrosoftEntra(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/providerMicrosoftEntra:ProviderMicrosoftEntra';

    /**
     * Returns true if the given object is an instance of ProviderMicrosoftEntra.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProviderMicrosoftEntra {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProviderMicrosoftEntra.__pulumiType;
    }

    public readonly clientId!: pulumi.Output<string>;
    public readonly clientSecret!: pulumi.Output<string>;
    /**
     * Defaults to `false`.
     */
    public readonly dryRun!: pulumi.Output<boolean | undefined>;
    public readonly excludeUsersServiceAccount!: pulumi.Output<boolean | undefined>;
    public readonly filterGroup!: pulumi.Output<string | undefined>;
    /**
     * Allowed values: - `delete` - `do_nothing` Defaults to `delete`.
     */
    public readonly groupDeleteAction!: pulumi.Output<string | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly propertyMappings!: pulumi.Output<string[] | undefined>;
    public readonly propertyMappingsGroups!: pulumi.Output<string[] | undefined>;
    public readonly providerMicrosoftEntraId!: pulumi.Output<string>;
    public readonly tenantId!: pulumi.Output<string>;
    /**
     * Allowed values: - `delete` - `do_nothing` Defaults to `delete`.
     */
    public readonly userDeleteAction!: pulumi.Output<string | undefined>;

    /**
     * Create a ProviderMicrosoftEntra resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderMicrosoftEntraArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProviderMicrosoftEntraArgs | ProviderMicrosoftEntraState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProviderMicrosoftEntraState | undefined;
            resourceInputs["clientId"] = state ? state.clientId : undefined;
            resourceInputs["clientSecret"] = state ? state.clientSecret : undefined;
            resourceInputs["dryRun"] = state ? state.dryRun : undefined;
            resourceInputs["excludeUsersServiceAccount"] = state ? state.excludeUsersServiceAccount : undefined;
            resourceInputs["filterGroup"] = state ? state.filterGroup : undefined;
            resourceInputs["groupDeleteAction"] = state ? state.groupDeleteAction : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["propertyMappings"] = state ? state.propertyMappings : undefined;
            resourceInputs["propertyMappingsGroups"] = state ? state.propertyMappingsGroups : undefined;
            resourceInputs["providerMicrosoftEntraId"] = state ? state.providerMicrosoftEntraId : undefined;
            resourceInputs["tenantId"] = state ? state.tenantId : undefined;
            resourceInputs["userDeleteAction"] = state ? state.userDeleteAction : undefined;
        } else {
            const args = argsOrState as ProviderMicrosoftEntraArgs | undefined;
            if ((!args || args.clientId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'clientId'");
            }
            if ((!args || args.clientSecret === undefined) && !opts.urn) {
                throw new Error("Missing required property 'clientSecret'");
            }
            if ((!args || args.tenantId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'tenantId'");
            }
            resourceInputs["clientId"] = args ? args.clientId : undefined;
            resourceInputs["clientSecret"] = args?.clientSecret ? pulumi.secret(args.clientSecret) : undefined;
            resourceInputs["dryRun"] = args ? args.dryRun : undefined;
            resourceInputs["excludeUsersServiceAccount"] = args ? args.excludeUsersServiceAccount : undefined;
            resourceInputs["filterGroup"] = args ? args.filterGroup : undefined;
            resourceInputs["groupDeleteAction"] = args ? args.groupDeleteAction : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["propertyMappings"] = args ? args.propertyMappings : undefined;
            resourceInputs["propertyMappingsGroups"] = args ? args.propertyMappingsGroups : undefined;
            resourceInputs["providerMicrosoftEntraId"] = args ? args.providerMicrosoftEntraId : undefined;
            resourceInputs["tenantId"] = args ? args.tenantId : undefined;
            resourceInputs["userDeleteAction"] = args ? args.userDeleteAction : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clientSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ProviderMicrosoftEntra.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ProviderMicrosoftEntra resources.
 */
export interface ProviderMicrosoftEntraState {
    clientId?: pulumi.Input<string>;
    clientSecret?: pulumi.Input<string>;
    /**
     * Defaults to `false`.
     */
    dryRun?: pulumi.Input<boolean>;
    excludeUsersServiceAccount?: pulumi.Input<boolean>;
    filterGroup?: pulumi.Input<string>;
    /**
     * Allowed values: - `delete` - `do_nothing` Defaults to `delete`.
     */
    groupDeleteAction?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    propertyMappings?: pulumi.Input<pulumi.Input<string>[]>;
    propertyMappingsGroups?: pulumi.Input<pulumi.Input<string>[]>;
    providerMicrosoftEntraId?: pulumi.Input<string>;
    tenantId?: pulumi.Input<string>;
    /**
     * Allowed values: - `delete` - `do_nothing` Defaults to `delete`.
     */
    userDeleteAction?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ProviderMicrosoftEntra resource.
 */
export interface ProviderMicrosoftEntraArgs {
    clientId: pulumi.Input<string>;
    clientSecret: pulumi.Input<string>;
    /**
     * Defaults to `false`.
     */
    dryRun?: pulumi.Input<boolean>;
    excludeUsersServiceAccount?: pulumi.Input<boolean>;
    filterGroup?: pulumi.Input<string>;
    /**
     * Allowed values: - `delete` - `do_nothing` Defaults to `delete`.
     */
    groupDeleteAction?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    propertyMappings?: pulumi.Input<pulumi.Input<string>[]>;
    propertyMappingsGroups?: pulumi.Input<pulumi.Input<string>[]>;
    providerMicrosoftEntraId?: pulumi.Input<string>;
    tenantId: pulumi.Input<string>;
    /**
     * Allowed values: - `delete` - `do_nothing` Defaults to `delete`.
     */
    userDeleteAction?: pulumi.Input<string>;
}
