// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class StageAuthenticatorEndpointGdtc extends pulumi.CustomResource {
  /**
   * Get an existing StageAuthenticatorEndpointGdtc resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: StageAuthenticatorEndpointGdtcState,
    opts?: pulumi.CustomResourceOptions,
  ): StageAuthenticatorEndpointGdtc {
    return new StageAuthenticatorEndpointGdtc(name, <any> state, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType = "authentik:index/stageAuthenticatorEndpointGdtc:StageAuthenticatorEndpointGdtc";

  /**
   * Returns true if the given object is an instance of StageAuthenticatorEndpointGdtc.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is StageAuthenticatorEndpointGdtc {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj["__pulumiType"] === StageAuthenticatorEndpointGdtc.__pulumiType;
  }

  public readonly configureFlow!: pulumi.Output<string | undefined>;
  public readonly credentials!: pulumi.Output<string>;
  public readonly friendlyName!: pulumi.Output<string | undefined>;
  public readonly name!: pulumi.Output<string>;
  public readonly stageAuthenticatorEndpointGdtcId!: pulumi.Output<string>;

  /**
   * Create a StageAuthenticatorEndpointGdtc resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args: StageAuthenticatorEndpointGdtcArgs, opts?: pulumi.CustomResourceOptions);
  constructor(
    name: string,
    argsOrState?: StageAuthenticatorEndpointGdtcArgs | StageAuthenticatorEndpointGdtcState,
    opts?: pulumi.CustomResourceOptions,
  ) {
    let resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as StageAuthenticatorEndpointGdtcState | undefined;
      resourceInputs["configureFlow"] = state ? state.configureFlow : undefined;
      resourceInputs["credentials"] = state ? state.credentials : undefined;
      resourceInputs["friendlyName"] = state ? state.friendlyName : undefined;
      resourceInputs["name"] = state ? state.name : undefined;
      resourceInputs["stageAuthenticatorEndpointGdtcId"] = state ? state.stageAuthenticatorEndpointGdtcId : undefined;
    } else {
      const args = argsOrState as StageAuthenticatorEndpointGdtcArgs | undefined;
      if ((!args || args.credentials === undefined) && !opts.urn) {
        throw new Error("Missing required property 'credentials'");
      }
      resourceInputs["configureFlow"] = args ? args.configureFlow : undefined;
      resourceInputs["credentials"] = args?.credentials ? pulumi.secret(args.credentials) : undefined;
      resourceInputs["friendlyName"] = args ? args.friendlyName : undefined;
      resourceInputs["name"] = args ? args.name : undefined;
      resourceInputs["stageAuthenticatorEndpointGdtcId"] = args ? args.stageAuthenticatorEndpointGdtcId : undefined;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    const secretOpts = { additionalSecretOutputs: ["credentials"] };
    opts = pulumi.mergeOptions(opts, secretOpts);
    super(
      StageAuthenticatorEndpointGdtc.__pulumiType,
      name,
      resourceInputs,
      opts,
      false, /*dependency*/
      utilities.getPackage(),
    );
  }
}

/**
 * Input properties used for looking up and filtering StageAuthenticatorEndpointGdtc resources.
 */
export interface StageAuthenticatorEndpointGdtcState {
  configureFlow?: pulumi.Input<string>;
  credentials?: pulumi.Input<string>;
  friendlyName?: pulumi.Input<string>;
  name?: pulumi.Input<string>;
  stageAuthenticatorEndpointGdtcId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a StageAuthenticatorEndpointGdtc resource.
 */
export interface StageAuthenticatorEndpointGdtcArgs {
  configureFlow?: pulumi.Input<string>;
  credentials: pulumi.Input<string>;
  friendlyName?: pulumi.Input<string>;
  name?: pulumi.Input<string>;
  stageAuthenticatorEndpointGdtcId?: pulumi.Input<string>;
}
