// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class StageMutualTls extends pulumi.CustomResource {
    /**
     * Get an existing StageMutualTls resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: StageMutualTlsState, opts?: pulumi.CustomResourceOptions): StageMutualTls {
        return new StageMutualTls(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/stageMutualTls:StageMutualTls';

    /**
     * Returns true if the given object is an instance of StageMutualTls.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StageMutualTls {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StageMutualTls.__pulumiType;
    }

    /**
     * Allowed values: - `subject` - `common_name` - `email` Defaults to `email`.
     */
    public readonly certAttribute!: pulumi.Output<string | undefined>;
    public readonly certificateAuthorities!: pulumi.Output<string[] | undefined>;
    /**
     * Allowed values: - `optional` - `required` Defaults to `optional`.
     */
    public readonly mode!: pulumi.Output<string | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly stageMutualTlsId!: pulumi.Output<string>;
    /**
     * Allowed values: - `username` - `email` Defaults to `email`.
     */
    public readonly userAttribute!: pulumi.Output<string | undefined>;

    /**
     * Create a StageMutualTls resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: StageMutualTlsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: StageMutualTlsArgs | StageMutualTlsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as StageMutualTlsState | undefined;
            resourceInputs["certAttribute"] = state ? state.certAttribute : undefined;
            resourceInputs["certificateAuthorities"] = state ? state.certificateAuthorities : undefined;
            resourceInputs["mode"] = state ? state.mode : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["stageMutualTlsId"] = state ? state.stageMutualTlsId : undefined;
            resourceInputs["userAttribute"] = state ? state.userAttribute : undefined;
        } else {
            const args = argsOrState as StageMutualTlsArgs | undefined;
            resourceInputs["certAttribute"] = args ? args.certAttribute : undefined;
            resourceInputs["certificateAuthorities"] = args ? args.certificateAuthorities : undefined;
            resourceInputs["mode"] = args ? args.mode : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["stageMutualTlsId"] = args ? args.stageMutualTlsId : undefined;
            resourceInputs["userAttribute"] = args ? args.userAttribute : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StageMutualTls.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering StageMutualTls resources.
 */
export interface StageMutualTlsState {
    /**
     * Allowed values: - `subject` - `common_name` - `email` Defaults to `email`.
     */
    certAttribute?: pulumi.Input<string>;
    certificateAuthorities?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Allowed values: - `optional` - `required` Defaults to `optional`.
     */
    mode?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    stageMutualTlsId?: pulumi.Input<string>;
    /**
     * Allowed values: - `username` - `email` Defaults to `email`.
     */
    userAttribute?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a StageMutualTls resource.
 */
export interface StageMutualTlsArgs {
    /**
     * Allowed values: - `subject` - `common_name` - `email` Defaults to `email`.
     */
    certAttribute?: pulumi.Input<string>;
    certificateAuthorities?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Allowed values: - `optional` - `required` Defaults to `optional`.
     */
    mode?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    stageMutualTlsId?: pulumi.Input<string>;
    /**
     * Allowed values: - `username` - `email` Defaults to `email`.
     */
    userAttribute?: pulumi.Input<string>;
}
