// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SystemSettings extends pulumi.CustomResource {
  /**
   * Get an existing SystemSettings resource's state with the given name, ID, and optional extra
   * properties used to qualify the lookup.
   *
   * @param name The _unique_ name of the resulting resource.
   * @param id The _unique_ provider ID of the resource to lookup.
   * @param state Any extra arguments used during the lookup.
   * @param opts Optional settings to control the behavior of the CustomResource.
   */
  public static get(
    name: string,
    id: pulumi.Input<pulumi.ID>,
    state?: SystemSettingsState,
    opts?: pulumi.CustomResourceOptions,
  ): SystemSettings {
    return new SystemSettings(name, <any> state, { ...opts, id: id });
  }

  /** @internal */
  public static readonly __pulumiType = "authentik:index/systemSettings:SystemSettings";

  /**
   * Returns true if the given object is an instance of SystemSettings.  This is designed to work even
   * when multiple copies of the Pulumi SDK have been loaded into the same process.
   */
  public static isInstance(obj: any): obj is SystemSettings {
    if (obj === undefined || obj === null) {
      return false;
    }
    return obj["__pulumiType"] === SystemSettings.__pulumiType;
  }

  /**
   * Defaults to `gravatar,initials`.
   */
  public readonly avatars!: pulumi.Output<string | undefined>;
  /**
   * Defaults to `minutes=30`.
   */
  public readonly defaultTokenDuration!: pulumi.Output<string | undefined>;
  /**
   * Defaults to `60`.
   */
  public readonly defaultTokenLength!: pulumi.Output<number | undefined>;
  /**
   * Defaults to `false`.
   */
  public readonly defaultUserChangeEmail!: pulumi.Output<boolean | undefined>;
  /**
   * Defaults to `true`.
   */
  public readonly defaultUserChangeName!: pulumi.Output<boolean | undefined>;
  /**
   * Defaults to `false`.
   */
  public readonly defaultUserChangeUsername!: pulumi.Output<boolean | undefined>;
  /**
   * Defaults to `days=365`.
   */
  public readonly eventRetention!: pulumi.Output<string | undefined>;
  public readonly footerLinks!: pulumi.Output<{ [key: string]: string }[] | undefined>;
  /**
   * Defaults to `true`.
   */
  public readonly gdprCompliance!: pulumi.Output<boolean | undefined>;
  /**
   * Defaults to `true`.
   */
  public readonly impersonation!: pulumi.Output<boolean | undefined>;
  /**
   * Defaults to `-5`.
   */
  public readonly reputationLowerLimit!: pulumi.Output<number | undefined>;
  /**
   * Defaults to `5`.
   */
  public readonly reputationUpperLimit!: pulumi.Output<number | undefined>;
  public readonly systemSettingsId!: pulumi.Output<string>;

  /**
   * Create a SystemSettings resource with the given unique name, arguments, and options.
   *
   * @param name The _unique_ name of the resource.
   * @param args The arguments to use to populate this resource's properties.
   * @param opts A bag of options that control this resource's behavior.
   */
  constructor(name: string, args?: SystemSettingsArgs, opts?: pulumi.CustomResourceOptions);
  constructor(
    name: string,
    argsOrState?: SystemSettingsArgs | SystemSettingsState,
    opts?: pulumi.CustomResourceOptions,
  ) {
    let resourceInputs: pulumi.Inputs = {};
    opts = opts || {};
    if (opts.id) {
      const state = argsOrState as SystemSettingsState | undefined;
      resourceInputs["avatars"] = state ? state.avatars : undefined;
      resourceInputs["defaultTokenDuration"] = state ? state.defaultTokenDuration : undefined;
      resourceInputs["defaultTokenLength"] = state ? state.defaultTokenLength : undefined;
      resourceInputs["defaultUserChangeEmail"] = state ? state.defaultUserChangeEmail : undefined;
      resourceInputs["defaultUserChangeName"] = state ? state.defaultUserChangeName : undefined;
      resourceInputs["defaultUserChangeUsername"] = state ? state.defaultUserChangeUsername : undefined;
      resourceInputs["eventRetention"] = state ? state.eventRetention : undefined;
      resourceInputs["footerLinks"] = state ? state.footerLinks : undefined;
      resourceInputs["gdprCompliance"] = state ? state.gdprCompliance : undefined;
      resourceInputs["impersonation"] = state ? state.impersonation : undefined;
      resourceInputs["reputationLowerLimit"] = state ? state.reputationLowerLimit : undefined;
      resourceInputs["reputationUpperLimit"] = state ? state.reputationUpperLimit : undefined;
      resourceInputs["systemSettingsId"] = state ? state.systemSettingsId : undefined;
    } else {
      const args = argsOrState as SystemSettingsArgs | undefined;
      resourceInputs["avatars"] = args ? args.avatars : undefined;
      resourceInputs["defaultTokenDuration"] = args ? args.defaultTokenDuration : undefined;
      resourceInputs["defaultTokenLength"] = args ? args.defaultTokenLength : undefined;
      resourceInputs["defaultUserChangeEmail"] = args ? args.defaultUserChangeEmail : undefined;
      resourceInputs["defaultUserChangeName"] = args ? args.defaultUserChangeName : undefined;
      resourceInputs["defaultUserChangeUsername"] = args ? args.defaultUserChangeUsername : undefined;
      resourceInputs["eventRetention"] = args ? args.eventRetention : undefined;
      resourceInputs["footerLinks"] = args ? args.footerLinks : undefined;
      resourceInputs["gdprCompliance"] = args ? args.gdprCompliance : undefined;
      resourceInputs["impersonation"] = args ? args.impersonation : undefined;
      resourceInputs["reputationLowerLimit"] = args ? args.reputationLowerLimit : undefined;
      resourceInputs["reputationUpperLimit"] = args ? args.reputationUpperLimit : undefined;
      resourceInputs["systemSettingsId"] = args ? args.systemSettingsId : undefined;
    }
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    super(SystemSettings.__pulumiType, name, resourceInputs, opts, false, /*dependency*/ utilities.getPackage());
  }
}

/**
 * Input properties used for looking up and filtering SystemSettings resources.
 */
export interface SystemSettingsState {
  /**
   * Defaults to `gravatar,initials`.
   */
  avatars?: pulumi.Input<string>;
  /**
   * Defaults to `minutes=30`.
   */
  defaultTokenDuration?: pulumi.Input<string>;
  /**
   * Defaults to `60`.
   */
  defaultTokenLength?: pulumi.Input<number>;
  /**
   * Defaults to `false`.
   */
  defaultUserChangeEmail?: pulumi.Input<boolean>;
  /**
   * Defaults to `true`.
   */
  defaultUserChangeName?: pulumi.Input<boolean>;
  /**
   * Defaults to `false`.
   */
  defaultUserChangeUsername?: pulumi.Input<boolean>;
  /**
   * Defaults to `days=365`.
   */
  eventRetention?: pulumi.Input<string>;
  footerLinks?: pulumi.Input<pulumi.Input<{ [key: string]: pulumi.Input<string> }>[]>;
  /**
   * Defaults to `true`.
   */
  gdprCompliance?: pulumi.Input<boolean>;
  /**
   * Defaults to `true`.
   */
  impersonation?: pulumi.Input<boolean>;
  /**
   * Defaults to `-5`.
   */
  reputationLowerLimit?: pulumi.Input<number>;
  /**
   * Defaults to `5`.
   */
  reputationUpperLimit?: pulumi.Input<number>;
  systemSettingsId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SystemSettings resource.
 */
export interface SystemSettingsArgs {
  /**
   * Defaults to `gravatar,initials`.
   */
  avatars?: pulumi.Input<string>;
  /**
   * Defaults to `minutes=30`.
   */
  defaultTokenDuration?: pulumi.Input<string>;
  /**
   * Defaults to `60`.
   */
  defaultTokenLength?: pulumi.Input<number>;
  /**
   * Defaults to `false`.
   */
  defaultUserChangeEmail?: pulumi.Input<boolean>;
  /**
   * Defaults to `true`.
   */
  defaultUserChangeName?: pulumi.Input<boolean>;
  /**
   * Defaults to `false`.
   */
  defaultUserChangeUsername?: pulumi.Input<boolean>;
  /**
   * Defaults to `days=365`.
   */
  eventRetention?: pulumi.Input<string>;
  footerLinks?: pulumi.Input<pulumi.Input<{ [key: string]: pulumi.Input<string> }>[]>;
  /**
   * Defaults to `true`.
   */
  gdprCompliance?: pulumi.Input<boolean>;
  /**
   * Defaults to `true`.
   */
  impersonation?: pulumi.Input<boolean>;
  /**
   * Defaults to `-5`.
   */
  reputationLowerLimit?: pulumi.Input<number>;
  /**
   * Defaults to `5`.
   */
  reputationUpperLimit?: pulumi.Input<number>;
  systemSettingsId?: pulumi.Input<string>;
}
