apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./blackbox_exporter.yaml
  - ./docker.yaml
  - ./hass.yaml
  - ./litter_robot.yaml
  - ./node_exporter.yaml
  - ./zonepop.yaml
