apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: litter-robot
spec:
  groups:
    - name: litter-robot
      rules:
        - alert: LitterRobotNoActivity
          expr: |
            rate(hass_state_change_total{entity="sensor.litter_robot_4_status_code"}[1d]) == 0
          for: 1d
          labels:
            severity: warning
          annotations:
            summary: Litter Robot hasn't done a clean cycle in a day.
        - alert: LitterRobotWasteFull
          expr: |
            hass_sensor_unit_percent{entity="sensor.litter_robot_4_waste_drawer"} > 90
          labels:
            severity: warning
          annotations:
            summary: Litter Robot waste drawer is full.
        - alert: LitterRobotLowLitterLevel
          expr: |
            hass_sensor_unit_percent{entity="sensor.litter_robot_4_litter_level"} < 50
          labels:
            severity: warning
          annotations:
            summary: Litter Robot litter level is starting to get low.
