apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: zonepop
spec:
  groups:
    - name: zonepop
      rules:
        - alert: ZonePopControllerFailing
          expr: rate(zonepop_controller_runs{status="errored"}[5m]) > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: ZonePop controller runs are failing
        - alert: ZonePopSourceDown
          expr: zonepop_source_up == 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: ZonePop source {{ $labels.source }} is down
        - alert: ZonePopProviderDown
          expr: zonepop_provider_up == 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: ZonePop provider {{ $labels.provider }} is down
        - alert: ZonePopControllerNotRunning
          expr: (time() - zonepop_controller_last_run_timestamp) > 600
          labels:
            severity: warning
          annotations:
            summary: ZonePop controller hasn't run in the last 10 minutes
